### ISSUE TITLE
can not compile on elixir 1.5

### ISSUE THREAD

**Issue by rohit06nitbpl** [takscape/elixir-array#5]
== Compilation error in file lib/array.ex ==
** (ArgumentError) Access is not a protocol
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    lib/array.ex:325: (file)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

**Comment by rohit06nitbpl** [comment]
wrote University assignment due tomorrow using this dep , very sad :(
